routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', 'StaticController@homePage')->name('home-page');


Route::resource('personas', 'employeeController');
Route::resource('puestos', 'positionController');
Route::resource('empleados_personas', 'employee_PositionController');

resources/views/empleado_puesto/_formulario.blade.php
 <h2>
    Asignar puesto
</h2>
    @if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Error!</strong> Revise los campos obligatorios.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
    @endif
    @if(Session::has('success'))
    <div class="alert alert-info">
    {{Session::get('success')}}
    </div>
@endif
<form method="POST" action="{{ route('empleados_personas.store') }}" >
    {{csrf_field()}}
    
    <div class="form-group">
        <label for="fecha">Empleado*</label>
        <select name="empleado" id="empleado"  class="form-control">
            <option value="" selected disabled>Selecciona un empleado</option>
            @foreach ($empleados as $empleado) 
            <option value="{{ $empleado->id }}">{{ $empleado->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="fecha">Puesto*</label>
        <select name="puesto" id="puesto"  class="form-control">
            <option value="" selected disabled>Selecciona un puesto</option>
            @foreach ($puestos as $puesto) 
            <option value="{{ $puesto->id }}">{{ $puesto->name }}</option>
            @endforeach
        </select>
    </div>
   

    <button type="submit" class="btn btn-default">Guardar</button>

</form>

resources/views/empleado_puesto/_tabla.blade.php
<div class="table-responsive">
    @if($empleados->count())  
    
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Puesto</th>
            <th>Modificar</th>
            <th>Eliminar</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($empleados as  $key => $employee)
            @foreach ($employee->positions as $puesto)
            <tr>
                <th scope="row">{{ $key+=1 }}</th>
                <td>{{ $employee->name }}</td>
                <td>{{ $puesto->name }}</td>
                 <td>
                    <a  href="{{ route('empleados_personas.edit', $puesto->pivot->id) }}" style="width: 100%;text-align: center;display: block;"><span class="glyphicon glyphicon-pencil" aria-hidden="true" data-id="{{ $puesto->id }}"></span></a>
                </td>
               <td>
                    <form method="POST" action="{{ route('empleados_personas.destroy', $puesto->pivot->id ) }}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit"  style="width: 100%;text-align: center;display: block;background: transparent;border: unset;" class="glyphicon glyphicon-trash"  aria-hidden="true"></button>
                    </form>
                
                </td>
            </tr>             
            @endforeach
        @endforeach
        </tbody>
    </table>
    @else
    <h2>No hay registros</h2>
    @endif
</div>

resources/views/empleado_puesto/edit.blade.php
@extends('layouts.layout')


@section('content')
  <div class="row">
    <section class="content">
      <div class="col-md-6 col-md-offset-3">
        <h2>
          Editar Asignar puesto
        </h2>
   			@if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                    <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>
            @endif
            @if(Session::has('success'))
                <div class="alert alert-info">
                    {{Session::get('success')}}
                </div>
            @endif
        <form method="POST" action="{{ route('empleados_personas.update', $relacion->id) }} " >
          {{csrf_field()}}
           {{ method_field('PUT') }}
            <div class="form-group">
              <label for="fecha">Empleado*</label>
              <select name="empleado" id="empleado"  class="form-control">
                  <option value="" disabled>Selecciona un empleado</option>
                  @foreach ($empleados as $empleado) 
                    @if ($empleado->id ==  $relacion->employee_id)
                      <option value="{{ $empleado->id }}" selected>{{ $empleado->name }}</option>  
                    @else
                      <option value="{{ $empleado->id }}">{{ $empleado->name }}</option>
                    @endif
                  @endforeach
              </select>
          </div>

          <div class="form-group">
              <label for="fecha">Puesto*</label>
              <select name="puesto" id="puesto"  class="form-control">
                  <option value="" disabled>Selecciona un puesto</option>
                  @foreach ($puestos as $puesto) 
                    @if ($puesto->id ==  $relacion->position_id)
                      <option value="{{ $puesto->id }}" selected>{{ $puesto->name }}</option>
                    @else
                      <option value="{{ $puesto->id }}">{{ $puesto->name }}</option>
                    @endif
                  @endforeach
              </select>
          </div>

          <button type="submit" class="btn btn-default">Guardar</button>

        </form>
      </div>
    </section>
  </div>
@endsection

resources/views/empleado_puesto/index.blade.php
@extends('layouts.layout')


@section('content')
  <div class="row">
    <section class="content">
      {{-- tabla muestra  puestos --}}
      <div class="col-md-7">
          @include('empleado_puesto._tabla')
      </div>
      {{-- formulario crea puestos --}}
      <div class="col-md-5">
          @include('empleado_puesto._formulario')
      </div>
    </section>
  </div>
@endsection