routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', 'StaticController@homePage')->name('home-page');


Route::resource('personas', 'employeeController');
Route::resource('puestos', 'positionController');
Route::resource('empleados_personas', 'employee_PositionController');

resources/views/home/_formulario.blade.php
 <h2>
    Ingesar nueva persona
</h2>
    @if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Error!</strong> Revise los campos obligatorios.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
    @endif
    @if(Session::has('success'))
    <div class="alert alert-info">
    {{Session::get('success')}}
    </div>
@endif
<form method="POST" action="{{ route('personas.store') }}" >
    {{csrf_field()}}
    <div class="form-group">
    <label for="nombre">Nombre*</label>
    <input type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" id="nombre" placeholder="Nombre">
    </div>

    <div class="form-group">
    <label for="apellido">Apellido*</label>
    <input type="text" class="form-control" name="apellido" value="{{ old('apellido') }}" id="apellido" placeholder="Apellido">
    </div>

    <div class="form-group">
    <label for="fecha">Fecha de nacimiento*</label>
    <input type="date" class="form-control" name="fecha" value="{{ old('fecha') }}" id="fecha" placeholder="Fecha">
    </div>
    
   
    
    <button type="submit" class="btn btn-default">Guardar</button>

</form>

resources/views/home/_tabla.blade.php
<div class="table-responsive">
    @if($empleados->count())  
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Fecha de nacimiento</th>
            <th>Modificar</th>
            <th>Eliminar</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($empleados as  $key => $empleado)
            <tr>
                <th scope="row">{{ $key+=1 }}</th>
                <td>{{ $empleado->name }}</td>
                <td>{{ $empleado->last_name }}</td>
                <td>{{  \Carbon\Carbon::parse($empleado->birth_date)->format('d-M-Y') }}</td>
                <td>
                    <a  href="{{ route('personas.edit', $empleado->id) }}" style="width: 100%;text-align: center;display: block;"><span class="glyphicon glyphicon-pencil" aria-hidden="true" data-id="{{ $empleado->id }}"></span></a>
                </td>
                <td>
                    <form method="POST" action="{{ route('personas.destroy', $empleado->id) }}">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit"  style="width: 100%;text-align: center;display: block;background: transparent;border: unset;" class="glyphicon glyphicon-trash"  aria-hidden="true"></button>
                </form>
                
                </td>
            </tr>             
        @endforeach
        </tbody>
    </table>
    @else
    <h2>No hay registros</h2>
    @endif
</div>

resources/views/home/index.blade.php
@extends('layouts.layout')


@section('content')
  <div class="row">
    <section class="content">
      {{-- tabla muestra usuarios --}}
      <div class="col-md-8">
          @include('home._tabla')
      </div>
      {{-- formulario crea usuario --}}
      <div class="col-md-4">
          @include('home._formulario')
      </div>
    </section>
  </div>
@endsection