routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', 'StaticController@homePage')->name('home-page');


Route::resource('personas', 'employeeController');
Route::resource('puestos', 'positionController');
Route::resource('empleados_personas', 'employee_PositionController');

resources/views/puestos/_formulario.blade.php
 <h2>
    Ingesar nuevo puesto
</h2>
    @if (count($errors) > 0)
    <div class="alert alert-danger">
    <strong>Error!</strong> Revise los campos obligatorios.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
    </div>
    @endif
    @if(Session::has('success'))
    <div class="alert alert-info">
    {{Session::get('success')}}
    </div>
@endif
<form method="POST" action="{{ route('puestos.store') }}" >
    {{csrf_field()}}
    <div class="form-group">
    <label for="nombre">Nombre*</label>
    <input type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" id="nombre" placeholder="Nombre">
    </div>
    <button type="submit" class="btn btn-default">Guardar</button>

</form>

resources/views/puestos/_tabla.blade.php
<div class="table-responsive">
    @if($puestos->count())  
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Modificar</th>
            <th>Eliminar</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($puestos as  $key => $puesto)
            <tr>
                <th scope="row">{{ $key+=1 }}</th>
                <td>{{ $puesto->name }}</td>
                <td>
                    <a  href="{{ route('puestos.edit', $puesto->id) }}" style="width: 100%;text-align: center;display: block;"><span class="glyphicon glyphicon-pencil" aria-hidden="true" data-id="{{ $puesto->id }}"></span></a>
                </td>
                <td>
                    <form method="POST" action="{{ route('puestos.destroy', $puesto->id) }}">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit"  style="width: 100%;text-align: center;display: block;background: transparent;border: unset;" class="glyphicon glyphicon-trash"  aria-hidden="true"></button>
                </form>
                
                </td>
            </tr>             
        @endforeach
        </tbody>
    </table>
    @else
    <h2>No hay registros</h2>
    @endif
</div>

resources/views/puestos/edit.blade.php
@extends('layouts.layout')


@section('content')
  <div class="row">
    <section class="content">
      <div class="col-md-6 col-md-offset-3">
        <h2>
          Editar {{ $position->name }}
        </h2>
   			@if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Error!</strong> Revise los campos obligatorios.<br><br>
                    <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>
            @endif
            @if(Session::has('success'))
                <div class="alert alert-info">
                    {{Session::get('success')}}
                </div>
            @endif
        <form method="POST" action="{{ route('puestos.update', $position->id) }} " >
          {{csrf_field()}}
           {{ method_field('PUT') }}
          <div class="form-group">
            <label for="nombre">Nombre*</label>
            <input type="text" class="form-control" name="nombre" value="{{ $position->name }}" id="nombre" placeholder="Nombre">
          </div>

          
          <button type="submit" class="btn btn-default">Guardar</button>

        </form>
      </div>
    </section>
  </div>
@endsection

resources/views/puestos/index.blade.php
@extends('layouts.layout')


@section('content')
  <div class="row">
    <section class="content">
      {{-- tabla muestra  puestos --}}
      <div class="col-md-7">
          @include('puestos._tabla')
      </div>
      {{-- formulario crea puestos --}}
      <div class="col-md-5">
          @include('puestos._formulario')
      </div>
    </section>
  </div>
@endsection